spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/kaamSet_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=your-very-long-secret-key-here-min-256-bits


